"""empty message

Revision ID: b0fbd8468e35
Revises: 8713a5f0f6ab
Create Date: 2021-02-08 14:22:09.144839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fbd8468e35'
down_revision = '8713a5f0f6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
